split:
  test_size: 0.2
  seed: 42

model_name: lightgbm
model_kwargs:
  random_state: 42
  objective: regression
  metric: rmse
  n_jobs: 4
  verbosity: -1
  force_col_wise: true
param_grid:
  n_estimators: [250, 400, 600]
  learning_rate: [0.01, 0.05]
  num_leaves: [15, 31]
  max_depth: [6, 10]
  min_child_samples: [20, 400]
